export const SELECT_VIDEO = 'SELECT_VIDEO'
export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'
export const SET_RESULTS = 'SET_RESULTS'
export const FETCH_RESULTS = 'FETCH_RESULTS'
